name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: cargo build --release

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/AnomalyLauncher.exe
          tag_name: "v${{ steps.date.outputs.DATE }}-${{ steps.sha.outputs.SHORT_SHA }}"
          generate_release_notes: true