name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Datetime
      id: datetime
      run: echo "::set-output name=today::$(date +'%-Y.%-m.%-d.%-H.%-M')"
    - name: Get Version
      run: echo "VERSION ${{steps.datetime.outputs.today}}"
      env:
        VERSION: "${{steps.datetime.outputs.today}}"
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Create Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/AnomalyLauncher.exe
        tag_name: "${{steps.datetime.outputs.today}}"
        generate_release_notes: true
